[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 50, lines=15 }
decorations = "Full"
opacity = 0.95
blur = true
title = "Terminal"
dynamic_title = false
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono NFM" }
size = 14

[colors.primary]
background = "#222226"
foreground = "#FFFFFF"

[colors.normal]
black = "#2E3436"
red = "#CC0000"
green = "#74E805"
yellow = "#C4A000"
blue = "#1C77EC"
magenta = "#75507B"
cyan = "#06989A"
white = "#D3D7CF"

[colors.bright]
black = "#555753"
red = "#EF2929"
green = "#8AE234"
yellow = "#FCE94F"
blue = "#729FCF"
magenta = "#AD7FA8"
cyan = "#34E2E2"
white = "#EEEEEC"
